#开发环境配置

server:
  # 服务端口
  port: 8080


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-wkik?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: abc123456
logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    com.skboy.wiki.mapper: debug




